---
apiVersion: v1
appVersion: "1.0.0"
description: A helm chart that deploys a docker image that echoes request data as JSON; listens on HTTP/S, useful for debugging.
name: http-https-echo-chart
version: 0.1.2
