---
# Default values for http-https-echo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mycluster.icp:8500/default/http-https-echo
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 8080
  httpsPort: 8443
