apiVersion: v1
kind: Service
metadata:
  name: 'watson-additional-service'
  labels:
    app.kubernetes.io/name: {{ include "http-https-echo.name" . }}
    helm.sh/chart: {{ include "http-https-echo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "http-https-echo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
